# A template for ci_integrations config with the Github Actions CI
# integration as a `source`.

source:
  github_actions:
    # A workflow identifier is either a workflow id or a name of the file that defines the workflow.
    workflow_identifier: ...

    # A name of the repository.
    #
    # In order to find the repository owner or the repository name, consider using the repository url:
    # https://github.com/REPOSITORY_OWNER/REPOSITORY_NAME.
    #
    repository_name: ...

    # An owner of the repository.
    #
    # In order to find the repository owner or the repository name, consider using the repository url:
    # https://github.com/REPOSITORY_OWNER/REPOSITORY_NAME.
    #
    repository_owner: ...

    # A Github personal access token.
    #
    # Generation guide: https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token.
    #
    access_token: ...

destination:

# Add your destination config here.
