steps:
  - label: "Dart analyze"
    key: "analyze"
    commands:
      - cd metrics/coverage_converter
      - pub get
      - dartanalyzer . --fatal-infos --fatal-warnings
    plugins:
      - docker-compose:
          config: ".buildkite/compose-files/dart-docker-compose.yml"
          run: dart
          propagate-uid-gid: true
          workdir: /monorepo

  - label: "Run tests"
    key: "tests"
    depends_on: "analyze"
    commands:
      - cd metrics/coverage_converter
      - pub get
      - pub run test_coverage --print-test-output --no-badge
      - coverage_converter lcov -i coverage/lcov.info -o coverage-summary.json
    plugins:
      - docker-compose:
          config: ".buildkite/compose-files/dart-docker-compose.yml"
          run: dart
          propagate-uid-gid: true
          workdir: /monorepo
    artifact_paths:
      - "metrics/coverage_converter/coverage/lcov.info"
      - "metrics/coverage_converter/coverage-summary.json"

  - label: "Finalize build"
    key: "finalize"
    depends_on:
      - step: "tests"
    commands:
      - echo "The build is completed."